	-- MySQL Script generated by MySQL Workbench
	-- Sat Jul  7 20:52:19 2018
	-- Model: New Model    Version: 1.0
	-- MySQL Workbench Forward Engineering

	SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

	-- -----------------------------------------------------
	-- Schema GLADIOSCEV
	-- -----------------------------------------------------

	-- -----------------------------------------------------
	-- Schema GLADIOSCEV
	-- -----------------------------------------------------
	CREATE SCHEMA IF NOT EXISTS `GLADIOSCEV` DEFAULT CHARACTER SET utf8 ;
	USE `GLADIOSCEV` ;
    
	-- -----------------------------------------------------
	-- Table `GLADIOSCEV`.`Produtos`
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `GLADIOSCEV`.`Produtos` (
	  `ID_Produto` INT NOT NULL,
	  `NomeProduto` VARCHAR(45) NOT NULL,
	  `DataAquisicao` DATETIME NOT NULL,
	  `Descricao` MEDIUMTEXT NULL,
	  `Quantidade` DECIMAL(10,2) NOT NULL,
	  `Unidade` CHAR(2) NOT NULL,
	  `PrecoAquisicao` DECIMAL(10,2) NOT NULL,
	  `PrecoVenda` DECIMAL(10,2) NOT NULL,
	  PRIMARY KEY (`ID_Produto`))
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `GLADIOSCEV`.`TiposMovimentos`
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `GLADIOSCEV`.`TiposMovimentos` (
	  `ID_TipoMovimento` INT NOT NULL,
	  `NomeMovimento` VARCHAR(45) NOT NULL,
	  `DebitoCredito` CHAR(1) NOT NULL,
	  PRIMARY KEY (`ID_TipoMovimento`))
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `GLADIOSCEV`.`MovimentosEstoque`
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `GLADIOSCEV`.`MovimentosEstoque` (
	  `ID_Movimento` INT NOT NULL,
	  `DataMovimento` DATETIME NOT NULL,
	  `ID_TipoMovimento` INT NOT NULL,
	  PRIMARY KEY (`ID_Movimento`),
	  INDEX `fk_MovimentosEstoque_TiposMovimentos_idx` (`ID_TipoMovimento` ASC),
	  CONSTRAINT `fk_MovimentosEstoque_TiposMovimentos`
		FOREIGN KEY (`ID_TipoMovimento`)
		REFERENCES `GLADIOSCEV`.`TiposMovimentos` (`ID_TipoMovimento`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `GLADIOSCEV`.`ProdutosMovimentos`
	-- -----------------------------------------------------
	CREATE TABLE IF NOT EXISTS `GLADIOSCEV`.`ProdutosMovimentos` (
	  `ID_ProdutoMovimento` INT NOT NULL,
	  `ID_Movimento` INT NOT NULL,
	  `ID_Produto` INT NOT NULL,
	  `Quantidade` DECIMAL(10,2) NOT NULL,
	  PRIMARY KEY (`ID_ProdutoMovimento`),
	  INDEX `fk_Movimento_idx` (`ID_Movimento` ASC),
	  INDEX `fk_Produto_idx` (`ID_Produto` ASC),
	  CONSTRAINT `fk_Movimento`
		FOREIGN KEY (`ID_Movimento`)
		REFERENCES `GLADIOSCEV`.`MovimentosEstoque` (`ID_Movimento`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	  CONSTRAINT `fk_Produto`
		FOREIGN KEY (`ID_Produto`)
		REFERENCES `GLADIOSCEV`.`Produtos` (`ID_Produto`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
	ENGINE = InnoDB;


	SET SQL_MODE=@OLD_SQL_MODE;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
	SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
